# Generated by Django 5.0.1 on 2024-02-23 17:24

import mypizzaApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypizzaApp', '0002_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', mypizzaApp.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
