# Generated by Django 5.0.1 on 2024-02-24 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypizzaApp', '0004_alter_order_address_alter_order_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='order_datetime',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_time',
        ),
    ]
